language: node_js
node_js:
  - 0.12
  - 4.0
  - 4
  - 5.0
  - 5
install:
  - npm install -g codecov
  - npm install -g babel-cli
  - npm install -g istanbul
  - npm install -g mocha
  - npm install
script:
  - npm test
after_success:
  - codecov
